import { nanoid } from "nanoid";
import { Pack } from "../types/interfaces";

export const gamePacks: Pack[] = [
  {
    id: "friends",
    name: "Friends Pack",
    description: "Fun questions for your squad",
    icon: "👯",
    color: "from-orange-500 to-amber-500",
    questions: [
      "What's the most embarrassing thing you've done in front of this group?",
      "Who here would you trust with your deepest secret?",
      "What's your guilty pleasure song that you blast when alone?",
      "If you could swap lives with someone in this room for a day, who would it be?",
      "What's the weirdest dream you've had about someone here?",
      "Who in this group is most likely to become famous?",
      "What's a habit you have that would surprise everyone here?",
      "If we were all in a horror movie, who would survive?",
      "What's the funniest memory you have with this group?",
      "Who here gives the best advice?",
      "What's something you've never told anyone in this room?",
      "Who would you call first if you won the lottery?",
    ],
  },
  {
    id: "family",
    name: "Family Pack",
    description: "Wholesome questions for family bonding",
    icon: "👨‍👩‍👧‍👦",
    color: "from-emerald-500 to-teal-500",
    questions: [
      "What's your favorite family tradition?",
      "What's the best advice a family member has given you?",
      "What's your earliest childhood memory?",
      "If you could relive any family vacation, which would it be?",
      "What's something you learned from your parents that you'll never forget?",
      "Who in the family makes you laugh the most?",
      "What's a skill you wish you had learned from a family member?",
      "What's the best meal someone in the family makes?",
      "What family story gets told at every gathering?",
      "What's something you appreciate about each person here?",
      "What's a family tradition you want to start or continue?",
      "What's the most valuable thing your family has taught you?",
    ],
  },
  {
    id: "couples",
    name: "Couples Pack",
    description: "Romantic questions for partners",
    icon: "💕",
    color: "from-pink-500 to-rose-500",
    questions: [
      "What was your first impression of me?",
      "What's your favorite memory of us together?",
      "What do you love most about our relationship?",
      "Where do you see us in 10 years?",
      "What's something I do that always makes you smile?",
      "What's a dream you want us to achieve together?",
      "What song reminds you of us?",
      "What's the most romantic thing I've done for you?",
      "What's something new you'd like us to try together?",
      "What do you think is our greatest strength as a couple?",
      "What's a small thing I do that means a lot to you?",
      "What's your favorite thing about waking up next to me?",
    ],
  },
  {
    id: "work",
    name: "Work Buddies Pack",
    description: "Fun questions for colleagues",
    icon: "💼",
    color: "from-blue-500 to-indigo-500",
    questions: [
      "What's the funniest thing that's happened at work?",
      "If you weren't in this job, what would you be doing?",
      "What's your go-to productivity hack?",
      "Who would you want on your team for a zombie apocalypse?",
      "What's the best work perk you've ever had?",
      "What's a skill you've learned from a coworker?",
      "What's your dream office setup?",
      "Who gives the best presentations?",
      "What's the most interesting project you've worked on?",
      "If our team was a TV show, what would it be called?",
      "What's your Monday morning routine?",
      "What's the best team lunch we've had?",
    ],
  },
  {
    id: "party",
    name: "Party Pack",
    description: "Spicy questions for bold groups",
    icon: "🎉",
    color: "from-purple-500 to-fuchsia-500",
    questions: [
      "What's the wildest thing on your bucket list?",
      "Truth: What's the last lie you told?",
      "What's your most unpopular opinion?",
      "What's the craziest thing you've done for love?",
      "If you could get away with any crime, what would it be?",
      "What's a secret talent nobody knows about?",
      "What's the most rebellious thing you've ever done?",
      "Who was your celebrity crush growing up?",
      "What's the weirdest food combination you enjoy?",
      "What's something you've done that you'd never do again?",
      "What's the most spontaneous decision you've ever made?",
      "What's the boldest move you've ever made?",
    ],
  },
  {
    id: "deep",
    name: "Deep Talks Pack",
    description: "Meaningful questions for reflection",
    icon: "🌙",
    color: "from-violet-500 to-purple-600",
    questions: [
      "What's a belief you've changed your mind about?",
      "What would you tell your younger self?",
      "What's something you're grateful for today?",
      "What does success mean to you?",
      "What's a fear you've overcome?",
      "What's the most important lesson life has taught you?",
      "What brings you genuine happiness?",
      "What legacy do you want to leave behind?",
      "What's a moment that changed your perspective on life?",
      "What does love mean to you?",
      "What's something you need to forgive yourself for?",
      "If today was your last day, what would you do?",
    ],
  },
];

export const getPackById = (id: string): Pack | undefined => {
  return gamePacks.find((pack) => pack.id === id);
};

export const mappedGamePacks = gamePacks.map((pack) => ({
  ...pack,
  questions: pack.questions.map((qText) => ({
    id: nanoid(),
    text: qText,
  })),
}));
